# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"\x1b\n\nOCRRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"8\n\x0fOCRBatchRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x15\n\rdet_batch_num\x18\x02 \x01(\x05\"#\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x03(\x02\x12\t\n\x01y\x18\x02 \x03(\x02\"U\n\tOCRResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12&\n\x0c\x62ounding_box\x18\x03 \x03(\x0b\x32\x10.ocr.BoundingBox\"]\n\x0bOCRResponse\x12\x1f\n\x07results\x18\x01 \x03(\x0b\x32\x0e.ocr.OCRResult\x12\x16\n\x0enum_detections\x18\x02 \x01(\x05\x12\x15\n\rjson_response\x18\x03 \x01(\x0c\"Q\n\x10OCRBatchResponse\x12\'\n\rbatch_results\x18\x01 \x03(\x0b\x32\x10.ocr.OCRResponse\x12\x14\n\x0ctotal_images\x18\x02 \x01(\x05\x32{\n\nOCRService\x12.\n\tRecognize\x12\x0f.ocr.OCRRequest\x1a\x10.ocr.OCRResponse\x12=\n\x0eRecognizeBatch\x12\x14.ocr.OCRBatchRequest\x1a\x15.ocr.OCRBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST']._serialized_start=18
  _globals['_OCRREQUEST']._serialized_end=45
  _globals['_OCRBATCHREQUEST']._serialized_start=47
  _globals['_OCRBATCHREQUEST']._serialized_end=103
  _globals['_BOUNDINGBOX']._serialized_start=105
  _globals['_BOUNDINGBOX']._serialized_end=140
  _globals['_OCRRESULT']._serialized_start=142
  _globals['_OCRRESULT']._serialized_end=227
  _globals['_OCRRESPONSE']._serialized_start=229
  _globals['_OCRRESPONSE']._serialized_end=322
  _globals['_OCRBATCHRESPONSE']._serialized_start=324
  _globals['_OCRBATCHRESPONSE']._serialized_end=405
  _globals['_OCRSERVICE']._serialized_start=407
  _globals['_OCRSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
